title: Etnos - Plataforma Educacional
description: >
  Projeto em Gestão de Tecnologia focado em jogos infantis para diversidade
  cultural.

theme: just-the-docs

url: https://joaojuniorbr.github.io/etnos
baseurl: /

nav_external_links:
  - title: Repositório Principal (GitHub)
    url: https://github.com/joaojuniorbr/etnos
    hide_icon: true

nav_sort: title
nav:
  - title: Apresentação do Projeto (Início)
    url: /
  - title: Entregas
    children:
      - title: Primeira Entrega - Projeto Interdisciplinar I
        url: /2025-p1

search_enabled: true
