sonar.projectKey=joaojuniorbr_etnos
sonar.organization=joaojuniorbr
sonar.host.url=https://sonarcloud.io

sonar.sources=packages,apps
sonar.tests=packages,apps
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**, **/*.d.ts, **/dist/**, **/build/**, **/coverage/**, apps/api/prisma/migrations/**

sonar.cpd.exclusions=**/*/index.ts, **/*/eslint.*, **/*/globals.css, **/*/tailwind.config.js, **/*/vite.config.ts

sonar.typescript.lcov.reportPaths=packages/*/coverage/lcov.info,apps/*/coverage/lcov.info

sonar.coverage.exclusions=apps/**/*,packages/eslint-config/**/*,packages/typescript-config/**/*,packages/tailwind-config/**/*,packages/types/**/*,**/*.stories.tsx,**/*.stories.ts,**/*.js,packages/tools/src/test/**/*,packages/ui/src/test/**/*,packages/ui/src/assets/index.ts,packages/performance/**/*,packages/analytics/**/*,**/*/vitest.config.ts,**/*/vitest.config.js
