sonar.projectKey=joaojuniorbr_etnos
sonar.organization=joaojuniorbr
sonar.host.url=https://sonarcloud.io

sonar.sources=packages,apps
sonar.tests=packages,apps
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**, **/*.d.ts, **/dist/**, **/build/**, **/coverage/**

sonar.cpd.exclusions=**/*/index.ts, **/*/eslint.*, **/*/globals.css, **/*/tailwind.config.js, **/*/vite.config.ts

sonar.typescript.lcov.reportPaths=packages/*/coverage/lcov.info,apps/*/coverage/lcov.info

sonar.coverage.exclusions=apps/**/*, \
                          packages/eslint-config/**/*, \
                          packages/typescript-config/**/*, \
                          packages/tailwind-config/**/*