sonar.projectKey=joaojuniorbr_etnos
sonar.organization=joaojuniorbr
sonar.host.url=https://sonarcloud.io

sonar.sources=packages,apps
sonar.tests=packages,apps
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.typescript.lcov.reportPaths=packages/*/coverage/lcov.info,apps/*/coverage/lcov.info
