site_name: Etnos
site_url: https://joaojuniorbr.github.io/etnos

theme:
  name: material
  language: pt-BR
  font:
    text: IBM Plex Sans
    code: Fira Code
  features:
    - navigation.expand
    - search.highlight
    - search.suggest

plugins:
  - search

nav:
  - Home: index.md
  - Entregas:
      - Entrega 01: 2025-p1.md
      - Entrega 02: 2025-p2.md
      - Wipex: 2025-wipex.md

site_dir: ../site
